Repository CodeSystem2022/Code-People-Cuarto-Semestre, pull requests merged in 2023-09, with the labels that each got.

#21 Entidad usuario
  Programación IV/Clase01/base_datos.uxf
  Programación IV/Clase01/usuario.py
Labels: Python

#36 index.html y style.css
  e-commerce2022/client/index.html
  e-commerce2022/client/js/index.js
  e-commerce2022/client/js/products.js
  e-commerce2022/client/media/guantesdelimpieza.png
  e-commerce2022/client/style.css
Labels: JavaScript

#52 Clase 03 python
  Programación IV/Clase01/tipo_bool.py
  Programación IV/Clase01/tipo_nan.py
  Programación IV/ProyectosPython/Clase01/Valores_infinitos.py
Labels: Python

#51 tipos booleanos y ciclos de control
  Programación IV/Clase01/Sistemas_numeracion.py
  Programación IV/Clase01/tipo_bool.py
  Programación IV/clase1/.idea/clase1.iml
  Programación IV/clase1/tipo_float.py
Labels: Python

#59 modificacion y agregado de imagenes
  PPS/consultas_on_demand/practica_profecional/templates/index.html
Labels: JavaScript, Python, Django
